import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import type { ParsedHomepage } from "./parsers/types";

const BANNER =
  "/** AUTO-GENERATED by scripts/wp/extract-wp-content.mts — do not edit by hand. */";

function serialize(value: unknown, indent = 0): string {
  const pad = "  ".repeat(indent);
  const padInner = "  ".repeat(indent + 1);

  if (value === null || value === undefined) return "undefined";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" || typeof value === "boolean") return String(value);

  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const lines = value.map(
      (item) => `${padInner}${serialize(item, indent + 1)},`,
    );
    return `[\n${lines.join("\n")}\n${pad}]`;
  }

  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>).filter(
      ([, v]) => v !== undefined,
    );
    if (entries.length === 0) return "{}";
    const lines = entries.map(
      ([key, v]) => `${padInner}${JSON.stringify(key)}: ${serialize(v, indent + 1)},`,
    );
    return `{\n${lines.join("\n")}\n${pad}}`;
  }

  return JSON.stringify(value);
}

function writeModule(
  outDir: string,
  fileName: string,
  exportName: string,
  typeName: string,
  data: unknown,
): void {
  const body = serialize(data, 0);
  const content = `${BANNER}
import type { ${typeName} } from "./types";

export const ${exportName} = ${body} as const satisfies readonly ${typeName}[];
`;
  writeFileSync(join(outDir, fileName), content, "utf8");
}

function writeMeta(outDir: string, sourcePageId: number): void {
  const generatedAt = new Date().toISOString();
  const content = `${BANNER}
import type { HomepageContentMeta } from "./types";

export const homepageContentMeta = {
  generatedAt: ${JSON.stringify(generatedAt)},
  sourcePageId: ${sourcePageId},
} as const satisfies HomepageContentMeta;
`;
  writeFileSync(join(outDir, "meta.ts"), content, "utf8");
}

export function emitContentModules(
  repoRoot: string,
  parsed: ParsedHomepage,
  sourcePageId: number,
): void {
  const outDir = join(repoRoot, "src/content");
  mkdirSync(outDir, { recursive: true });

  writeModule(outDir, "services.ts", "serviceCards", "ServiceCardColumn", parsed.services);
  writeModule(outDir, "clients.ts", "clientLogos", "ClientLogo", parsed.clients);
  writeModule(outDir, "testimonials.ts", "testimonials", "Testimonial", parsed.testimonials);
  writeModule(outDir, "rotating.ts", "rotatingPhrases", "RotatingPhrase", parsed.rotatingPhrases);
  writeModule(outDir, "sections.ts", "contentSections", "ContentSection", parsed.sections);
  writeMeta(outDir, sourcePageId);

  const index = `${BANNER}
export * from "./types";
export { textBands } from "./text-bands";
export { serviceBlocks } from "./service-blocks";
export { serviceCards } from "./services";
export { clientLogos } from "./clients";
export { testimonials } from "./testimonials";
export { rotatingPhrases } from "./rotating";
export { contentSections } from "./sections";
export { homepageContentMeta } from "./meta";
`;
  writeFileSync(join(outDir, "index.ts"), index, "utf8");
}
