/** AUTO-GENERATED by scripts/wp/extract-wp-content.mts — do not edit by hand. */
import type { ClientLogo } from "./types";

export const clientLogos = [
  {
    "name": "Brand Name 01",
    "src": "/assets/clients/un-logo-1a.webp",
  },
  {
    "name": "Brand Name 02",
    "src": "/assets/clients/who-logo-500px.webp",
  },
  {
    "name": "Brand Name 03",
    "src": "/assets/clients/unicef-logo-white-1.webp",
  },
  {
    "name": "Brand Name 04",
    "src": "/assets/clients/unwomen-logo.webp",
  },
  {
    "name": "Brand Name 05",
    "src": "/assets/clients/msg-logo-1.webp",
  },
  {
    "name": "Brand Name 06",
    "src": "/assets/clients/glg-logo-white-1.webp",
  },
] as const satisfies readonly ClientLogo[];
