/** AUTO-GENERATED by scripts/wp/extract-wp-content.mts — do not edit by hand. */
import type { HomepageContentMeta } from "./types";

export const homepageContentMeta = {
  generatedAt: "2026-06-11T18:04:38.778Z",
  sourcePageId: 375,
} as const satisfies HomepageContentMeta;
