/** AUTO-GENERATED by scripts/wp/extract-wp-content.mts — do not edit by hand. */
import type { RotatingPhrase } from "./types";

export const rotatingPhrases = [
  {
    "text": "Web Design",
  },
  {
    "text": "Web Dev",
  },
  {
    "text": "Web Hosting",
  },
] as const satisfies readonly RotatingPhrase[];
