/** AUTO-GENERATED by scripts/wp/extract-wp-content.mts — do not edit by hand. */
import type { ContentSection } from "./types";

export const contentSections = [
  {
    "id": "partner-intro",
    "kind": "partner-intro",
    "title": "I partner with organizations to solve complex technology challenges and build digital products that drive measurable growth",
  },
  {
    "id": "un-advisor",
    "kind": "advisor",
    "title": "Served as a trusted United Nations advisor and resource to dozens of global organizations",
  },
  {
    "id": "brand-manifesto",
    "kind": "manifesto",
    "title": "Utilizing experience and creativity to break the mold and craft digital experiences that defy the status quo. Harnessing the cutting-edge technologies of today, we disrupt, innovate and shape the behaviors of tomorrow.",
  },
  {
    "id": "cta-band",
    "kind": "cta-band",
    "title": "START WORKING WITH ME",
    "bodyText": "If you're facing any technology-related challenges hindering your growth, let's talk.",
    "cta": {
      "label": "Let's talk",
      "href": "/contact/",
    },
  },
] as const satisfies readonly ContentSection[];
