/** AUTO-GENERATED by scripts/wp/extract-wp-content.mts — do not edit by hand. */
import type { ServiceCardColumn } from "./types";

export const serviceCards = [
  {
    "id": "ai-for-social-impact",
    "title": "AI for Social Impact",
    "image": "/wp-migrated/2025/02/home-04.webp",
    "items": [
      {
        "label": "AI for Social Impact",
        "href": "#",
      },
      {
        "label": "AI Hands On Training",
        "href": "#",
      },
      {
        "label": "AI Agent Creation",
        "href": "#",
      },
      {
        "label": "Zero to Mastery Training",
        "href": "#",
      },
      {
        "label": "Image & Video Generation",
        "href": "#",
      },
    ],
  },
  {
    "id": "wordpress",
    "title": "WordPress",
    "image": "/wp-migrated/2025/02/home-03.webp",
    "items": [
      {
        "label": "WordPress",
        "href": "#",
      },
      {
        "label": "Search Engine Optimization (SEO)",
        "href": "#",
      },
      {
        "label": "Web Applications",
        "href": "#",
      },
      {
        "label": "E-Commerce",
        "href": "#",
      },
      {
        "label": "WIX",
        "href": "#",
      },
      {
        "label": "Shopify",
        "href": "#",
      },
      {
        "label": "Sell Products on Social Media & Web",
        "href": "#",
      },
    ],
  },
  {
    "id": "microsoft-cloud",
    "title": "Microsoft Cloud",
    "image": "/wp-migrated/2025/02/home-05.webp",
    "items": [
      {
        "label": "Microsoft Cloud",
        "href": "#",
        "description": "M365",
      },
      {
        "label": "Google Cloud Platform",
        "href": "#",
        "description": "GCP",
      },
      {
        "label": "AWS Cloud",
        "href": "#",
        "description": "AWS",
      },
      {
        "label": "Non-Profit Cloud",
        "href": "#",
        "description": "Certified",
      },
      {
        "label": "Migration to Cloud",
        "href": "#",
      },
      {
        "label": "Multi-Cloud Solutions",
        "href": "#",
        "description": "Hybrid",
      },
      {
        "label": "Cloud Security & Backup",
        "href": "#",
        "description": "Certified",
      },
    ],
  },
] as const satisfies readonly ServiceCardColumn[];
