/** AUTO-GENERATED by scripts/wp/extract-wp-content.mts — do not edit by hand. */
import type { Testimonial } from "./types";

export const testimonials = [
  {
    "quote": "Before Dame Luthas joined our cause, our digital operations were fragmented and insecure, holding back our ability to scale. Dame Luthas didn’t just give us tools; they delivered a cohesive strategy. They guided us through a critical migration from Google…",
    "author": "Maria Sanchez",
    "role": "ALU",
  },
  {
    "quote": "Out here, communication is our lifeline. It’s how we coordinate, how we stay safe, and how we connect with headquarters. In the past, new system rollouts could be disruptive, leaving us with unreliable service when we needed it most. The…",
    "author": "Lt. Sofia Reyes",
    "role": "UNWomen Liaison",
  },
  {
    "quote": "As an organizer on the ground, trust is everything. The new website and secure Cognito forms Dame Luthas built meant that for the first time, workers felt truly safe submitting their information online. What really empowered us was the automation…",
    "author": "Jamal Washington",
    "role": "ALU",
  },
  {
    "quote": "My team is responsible for setting up communications in war zones and disaster areas. Before FOBOS, every deployment was a white-knuckle experience. Dame Luthas didn’t just understand our technical needs; he understood the pressure we were under. The FOBOS tool…",
    "author": "Kenji Tanaka",
    "role": "UNICC Managed Services",
  },
  {
    "quote": "In the complex environment of United Nations global operations, deploying new communication systems was traditionally a significant logistical challenge, fraught with delays and instability. The FOBOS solution, architected and delivered by Dame Luthas, was nothing short of transformative. It wasn’t…",
    "author": "Dr. Alistair Finch",
    "role": "UNDP",
  },
] as const satisfies readonly Testimonial[];
